name: Build and Test ASP.NET

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    # Use an Ubuntu runner
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up .NET 8.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  # Specify .NET 8.0 version

    # Step 3: Restore NuGet packages
    - name: Restore NuGet packages
      run: dotnet restore

    # Step 4: Build the project in Release configuration
    - name: Build
      run: dotnet build --configuration Release

    # Step 5: Run tests in Release configuration
    - name: Test
      run: dotnet test --configuration Release
